Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,7 +11,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-
+    
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
@@ -61,12 +61,12 @@ jobs:
          cp flipperzero-firmware/build/f7-firmware-D/cec_test_tool.fap release/
         elif [ -f flipperzero-firmware/build/f7-firmware-R/cec_test_tool.fap ]; then
          cp flipperzero-firmware/build/f7-firmware-R/cec_test_tool.fap release/
-        else
-         echo "App .fap file not found!"
-         exit 1
-         fi
-         cp README.md release/
-         cp CHANGELOG.md release/
+         else
+          echo "App .fap file not found!"
+          exit 1
+        fi
+        cp README.md release/
+        cp CHANGELOG.md release/
         
         # Create installation instructions
         cat > release/INSTALL.md << 'EOF'
